-- DDL
create table wifi_logs (
    id bigint generated by default as identity primary key,
    device_id text not null,
    minute int not null,
    status text not null,
    inserted_at timestamptz default now(),
    ist_timestamp TIMESTAMP GENERATED ALWAYS AS (
        inserted_at AT TIME ZONE 'Asia/Kolkata'
    ) STORED,
    asofdate VARCHAR(10)
);

-- DML
ALTER TABLE wifi_logs
ADD CONSTRAINT unique_device_minute_date
UNIQUE (device_id, minute, asofdate);